# default configuration
baseURL = "http://examplesite.com"
languageCode = "pt-br"
summaryLength = "10"
theme = "kross-hugo"
title = "Skylab"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "sobre"
name = "Sobre"
weight = 1

[[menu.main]]
URL = "apresentacoes"
name = "Apresentações"
weight = 2

[[menu.main]]
URL = "visitas"
name = "Visitas"
weight = 3

[[menu.main]]
URL = "contact"
name = "Local"
weight = 4


# default parameters
[params]
home = "Início"
logo = ""
# theme color
theme_color = "#1e348a"
# contact info
phone = "+880 2544 658 256"
email = "steve.fruits@email.com"
address = "Av. Maurício de Nassau - Iputinga. Recife -PE, 50711-445"
# meta description
author = "Ingridy Souza"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
#gmap_api = "https://www.google.com/maps/place/USF+SKYLAB/@-8.0383993,-34.9325923,17z/data=!4m5!3m4!1s0x0:0x93e17264b426e5e9!8m2!3d-8.0386543!4d-34.9306611"
map_latitude = "-8.0383993"
map_longitude = "-34.9325923"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-dribbble"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
